<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-add-to-cart</name>
   <tag></tag>
   <elementGuidId>8f5403f9-1f55-4451-ba3f-994608704c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-add-to-cart</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
