<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart-products-name</name>
   <tag></tag>
   <elementGuidId>21675a5b-12f2-4ed7-ac99-b74d3b34ed03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart-products__name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
