<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-cart</name>
   <tag></tag>
   <elementGuidId>4230f9f2-a2cf-4ed5-9080-f39af1950641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.icon-cart</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
