<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lg</name>
   <tag></tag>
   <elementGuidId>031d533e-448f-4bdb-939d-4845ea1e6de0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ReactModal__Content--after-open</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
