<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification</name>
   <tag></tag>
   <elementGuidId>56051f6e-e7cb-4dfd-93a9-e77ed9e24de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slidedown-footer>button:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
