<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>products</name>
   <tag></tag>
   <elementGuidId>6be3807c-52d8-4966-a478-f9dadd72044c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.name>span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
